title:              GlockTian
email:              petertianzhong@gmail.com
description:        Hi! Visitor! This is where I publish my blogs!
author:             Peter Zhong
baseurl:            ""
url:                ""

# Social Profiles
# twitter_username:   SBootstrap
# github_username:    StartBootstrap
# facebook_username:  StartBootstrap
# instagram_username:  
# linkedin_username:

# Add your google-analytics ID here to activate google analytics
# google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

# Set which comment system to use
comments:
  # 'disqus' or 'utterances' are available
  provider:            giscus
# You must install utterances github app before use.(https://github.com/apps/utterances)
# Make sure all variables are set properly. Check below link for detail.
# https://utteranc.es/
# utterances:
#   repo:                "LazyRen/LazyRen.github.io"
#   issue-term:          "pathname"
#   label:               "Comments"
#   theme:               "dark-blue"

# You must install giscus github app before use.(https://github.com/apps/giscus)
# Make sure all variables are set properly. Check below link for detail.
# https://giscus.vercel.app/
giscus:
  repo:                "GlockTian/GlockTian.github.io"
  repo-id:             "MDEwOlJlcG9zaXRvcnkzODc5NzAwMzg="
  category:            "General"
  category-id:         "DIC_kwDOFx_z9s4COopT"
  mapping:             "pathname"
  reaction-enabled:    "1"
  theme:               "light"
  crossorigin:         "anonymous"